apiVersion: batch/v1
kind: CronJob
metadata:
  name: naver-text-crawler
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawing
            image: joron1827/pyarrow:v3
            imagePullPolicy: IfNotPresent
            env:
            - name: HDFS
              valueFrom:
                secretKeyRef:
                  name: passed-in-args
                  key: hdfs
            - name: HDFSPORT
              valueFrom:
                secretKeyRef:
                  name: passed-in-args
                  key: hdfsport
            - name: HDFSPATH
              valueFrom:
                secretKeyRef:
                  name: passed-in-args
                  key: hdfspath
            command:
            - sh
            - -c
            - >
              git clone https://github.com/joron1827/Stock_docs_classify.git && python ./Stock_docs_classify/crawler_using_db_hdfs/main.py -hdfs ${HDFS} -hdfsPort ${HDFSPORT} -hdfsPath ${HDFSPATH}
          restartPolicy: OnFailure