apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: flask
spec:
  selector:
    app: flask-app
    component: singleuser-server
  ports:
    - name: driver
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: blockmanager
      protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP